environment:
  CHANNEL: nightly
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TARGET: x86_64-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      TARGET: x86_64-apple-darwin
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      TARGET: x86_64-unknown-linux-gnu

build: false

# TBD: Install rustup from install.ps1!
install:
  - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-host $TARGET --default-toolchain $CHANNEL --profile minimal -y
  - sh: source $HOME/.cargo/env
  - cmd: appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% --profile minimal -y
  - rustc -Vv
  - cargo --version
  - ps: .\scripts\install.ps1

build_script:
  - ps: .\scripts\build.ps1

test_script:
  - ps: .\scripts\test.ps1

artifacts:
  - path: _artifacts/build.txt
  - path: _artifacts/version.txt
  - name: zip
    path: _artifacts/*.zip

deploy:
  description: Official release
  artifact: zip
  auth_token:
    secure: KnsNe82iVYE0/gNPx55EdNiJ3q5rM9GKu+y8E/Fz5tCnybP3NZj0PEbLabX9wZzY
  provider: GitHub
  on:
    APPVEYOR_REPO_TAG: true
