environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build: false

install:
  - ps: .\scripts\install.ps1 -DumpEnv -Detailed -RustupInit

build_script:
  - ps: .\scripts\build.ps1

test_script:
  - ps: .\scripts\test.ps1

artifacts:
  - path: target/dist/build.txt
  - path: target/dist/version.txt
  - name: zip
    path: target/dist/*.zip

deploy:
  description: Official release
  artifact: zip
  auth_token:
    secure: KnsNe82iVYE0/gNPx55EdNiJ3q5rM9GKu+y8E/Fz5tCnybP3NZj0PEbLabX9wZzY
  provider: GitHub
  on:
    APPVEYOR_REPO_TAG: true
