environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build: false

install:
  - ps: .\scripts\install.ps1

build_script:
  - ps: .\scripts\build.ps1

test_script:
  - ps: .\scripts\test.ps1

artifacts:
  - path: _artifacts/build.txt
  - path: _artifacts/version.txt
  - path: _artifacts/*.zip

deploy:
  description: Official release
  artifact: _artifacts/*.zip
  auth_token:
    secure: %GitHub_auth_token%
  provider: GitHub
  on:
    branch: master
#    APPVEYOR_REPO_TAG: true
