environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build: false

install:
  - ps: .\install.ps1 -DumpEnv

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1

artifacts:
  - path: _artifacts/build.txt
  - path: _artifacts/version.txt
  - path: _artifacts/*.zip
