environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build: false

install:
  - ps: Write-Output "t=$($env:GitHub_auth_token)"
  - ps: Write-Output "t=$($env:SUPER_SECRET)"
  - ps: .\scripts\install.ps1

build_script:
  - ps: .\scripts\build.ps1

test_script:
  - ps: .\scripts\test.ps1

artifacts:
  - path: _artifacts/build.txt
  - path: _artifacts/version.txt
  - name: zip
    path: _artifacts/*.zip

deploy:
  description: Official release
  artifact: zip
  auth_token:
    secure: KnsNe82iVYE0/gNPx55EdNiJ3q5rM9GKu+y8E/Fz5tCnybP3NZj0PEbLabX9wZzY
  provider: GitHub
  on:
    branch: master
#    APPVEYOR_REPO_TAG: true
