environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

install:
  - ps: $ErrorActionPreference = 'Stop'
  - ps: .\probe.ps1

build: false

build_script:
  - echo build_script

test_script:
  - echo test_script

artifacts:
  - path: _artifacts/*.zip
