#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)

APPVEYOR_BUILD_FOLDER=$this_dir \
APPVEYOR_REPO_TAG=true \
APPVEYOR_REPO_BRANCH=v100 \
APPVEYOR_PROJECT_SLUG=ciprobe \
  pwsh $this_dir/build.ps1 $*
