#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)

APPVEYOR_BUILD_FOLDER=$this_dir \
APPVEYOR_REPO_TAG=false \
APPVEYOR_REPO_BRANCH=rcook-appveyor-notes \
APPVEYOR_PROJECT_SLUG=ciprobe \
  pwsh $this_dir/probe.ps1 $*
