#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)

export APPVEYOR_BUILD_FOLDER=$this_dir
export APPVEYOR_REPO_TAG=true
export APPVEYOR_REPO_BRANCH=v101
export APPVEYOR_PROJECT_SLUG=ciprobe

pwsh $this_dir/scripts/install.ps1
pwsh $this_dir/scripts/build.ps1
pwsh $this_dir/scripts/test.ps1
